// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY4OdHzqBZCdZNkAJ-V9fBJwwBEOhoNTs',
    appId: '1:192335288214:web:97db4f4211b12f0d7f2fb7',
    messagingSenderId: '192335288214',
    projectId: 'fir-learn-e99f4',
    authDomain: 'fir-learn-e99f4.firebaseapp.com',
    storageBucket: 'fir-learn-e99f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqRq8FbiCj6mLAWXa4AsR6ilOSfCIdxZA',
    appId: '1:192335288214:android:4a06001146c9b1787f2fb7',
    messagingSenderId: '192335288214',
    projectId: 'fir-learn-e99f4',
    storageBucket: 'fir-learn-e99f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYZekf8uWywRoUL4pBlz-POZtIcSNP2rA',
    appId: '1:192335288214:ios:f097134eb23d66467f2fb7',
    messagingSenderId: '192335288214',
    projectId: 'fir-learn-e99f4',
    storageBucket: 'fir-learn-e99f4.appspot.com',
    iosBundleId: 'com.example.firebaseInitial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYZekf8uWywRoUL4pBlz-POZtIcSNP2rA',
    appId: '1:192335288214:ios:f097134eb23d66467f2fb7',
    messagingSenderId: '192335288214',
    projectId: 'fir-learn-e99f4',
    storageBucket: 'fir-learn-e99f4.appspot.com',
    iosBundleId: 'com.example.firebaseInitial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY4OdHzqBZCdZNkAJ-V9fBJwwBEOhoNTs',
    appId: '1:192335288214:web:5ce0777b84cf78ac7f2fb7',
    messagingSenderId: '192335288214',
    projectId: 'fir-learn-e99f4',
    authDomain: 'fir-learn-e99f4.firebaseapp.com',
    storageBucket: 'fir-learn-e99f4.appspot.com',
  );
}
